#!/bin/bash
if [ -z "$1" ]; then
	echo "Usage: $0 ip_addr [fru]"
	echo
	echo "  Default FRU = 30 (AMC13 Slot)"
	exit 1
fi

IP="$1"; shift
FRU="${1:-30}"; shift

ipmitool -H $IP -U '' -P '' -t 0x82 -b 0 raw 0x2c 0x04 0x00 $FRU 0x00 >/dev/null
